sudo: required
dist: trusty
language: c

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - doxygen

install:
    - wget https://cmocka.org/files/1.0/cmocka-1.0.1.tar.xz
    - tar -xvf cmocka-1.0.1.tar.xz
    - cd cmocka-1.0.1
    - mkdir build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug ..
    - make
    - sudo make install
    - cd ../..
    - rm -rf cmocka-1.0.1

script:
  - mkdir build
  - cd build
  - ../configure
  - make
  - make clean
  - cd ..
  - ./configure --disable-documentation
  - make
  - cd example/simple
  - make
  - ./simple_example.out
  - cd ../..
  - ./clean.sh
  - cd tests
  - ./run_tests.sh
  - ./complete_test.sh
